version: '3'
services:
  kds-node:
    container_name: kds-container
    image: kds
    build: .
    ports:
     - "8080:8080"
  # mongo:
  #   image: 'mongo'
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - 'mongo:/data/db'